services:
  nextjs-app:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://register.pfe.mpstmeacm.com/"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3